# Generated by Django 5.2 on 2025-05-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='method',
            name='description',
        ),
        migrations.AddField(
            model_name='method',
            name='selector',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='method',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
